### PR TITLE
Updgrade to Tb115

### PR DESCRIPTION
**Pull request by caligraf**

### CODE REVIEW

**Comment by BillH99999** [comment]
@caligraf

Thank you so much. I'm really glad you were able to make it work for TB 115. I installed it and it is working here.

Thanks,

Bill

**Comment by BillH99999** [comment]
Oops... I spoke too soon.  It seems to be working if I use the right click context menu or the delete key or the delete button on the message window toolbar, but not if I select a message and then use the delete button on the unified toolbar.

Bill

**Comment by caligraf** [comment]
Sorry I didn't test this delete button on unified toolbar, I will fix it.
Olivier

________________________________
De : BillH99999 ***@***.***>
Envoyé : dimanche 17 septembre 2023 01:11
À : caligraf/ConfirmBeforeDelete ***@***.***>
Cc : caligraf ***@***.***>; Mention ***@***.***>
Objet : Re: [caligraf/ConfirmBeforeDelete] Updgrade to Tb115 (PR #17)


Oops... I spoke too soon. It seems to be working if I use the right click context menu or the delete key or the delete button on the message window toolbar, but not if I select a message and then use the delete button on the unified toolbar.

Bill

**Comment by BillH99999** [comment]
Thanks Olivier.... everything I've tried works now.

Bill

**Pull request merged**
